### ISSUE TITLE
Cannot read properties of undefined (reading 'channel_list')

### ISSUE THREAD

**Issue by sansonifabio** [bropat/ioBroker.eusec#269]
### Adapter version

0.9.4

### JS-Controller version

4.0.23

### Node version

v16.16.0

### Operating System type

Linux

### Operating system version

 Debian amd 64 

### Describe the bug

Guten morgen Bropat,
seit dem letzten Update habe ich jeden Tag diesen Fehlermeldung, vor der 0.9.4 hatte ich sie nicht kannst du helfen?
Grüße
Fabio
---------------------------------------------------------------------------------------------------------------------------------

2022-08-04 05:34:16.431	error	Cannot read properties of undefined (reading 'channel_list')

host.nuc
2022-08-04 05:34:19.642	error	instance system.adapter.eusec.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

eusec.0
2022-08-04 05:34:19.620	error	DB closed

eusec.0
2022-08-04 05:34:19.620	error	Error: DB closed at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:642:26) at Socket.emit (node:events:527:28) at TCP.<anonymous> (node:net:709:12)

eusec.0
2022-08-04 05:34:19.620	error	unhandled promise rejection: DB closed

eusec.0
2022-08-04 05:34:19.619	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

eusec.0
2022-08-04 05:34:16.430	error	TypeError: Cannot read properties of undefined (reading 'channel_list') at Station.getArmDelay (/opt/iobroker/node_modules/eufy-security-client/build/http/station.js:530:41) at Station.onAlarmMode (/opt/iobroker/node_modules/eufy-security-client/build/http/station.js:501:31) at P2PClientProtocol.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/build/http/station.js:33:57) at P2PClientProtocol.emit (node:events:527:28) at P2PClientProtocol.handleDataControl (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:1185:22) at P2PClientProtocol.handleData (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:899:18) at P2PClientProtocol.parseDataMessage (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:891:26) at P2PClientProtocol.handleMsg (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:718:26) at Socket.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:76:56) at Socket.emit (node:events:527:28)

eusec.0
2022-08-04 05:34:16.426	error	unhandled promise rejection: Cannot read properties of undefined (reading 'channel_list')

eusec.0
2022-08-04 05:34:16.426	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

eusec.0
2022-08-04 05:34:16.422	info	Alarm mode for station T8010N231949117B changed to: HOME

### To reproduce

**Der Fehler tritt auf wenn ich in der Eufy App unter Sicherheit meine Stationen umschalte zum Beispiel von zu Hause in einen von mir erstellten Modus schalte sprich von zu Hause in zum Beispiel Gute Nacht Modus. Dann gibt quasi der Adapter in Echtzeit die Fehler aus.**

**Comment by bropat** [comment]
https://github.com/bropat/eufy-security-client/issues/196

**Comment by bropat** [comment]
Wird beim nächsten Release behoben.

**Comment by sansonifabio** [comment]
> Wird beim nächsten Release behoben.

Ich danke dir bropat

**Comment by bropat** [comment]
Wurde in version `0.9.5` behoben.

**Comment by sansonifabio** [comment]
Vielen Dank @bropat ;-)
