### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'channel_list') at Station.getArmDelay 

### ISSUE THREAD

**Issue by sansonifabio** [bropat/ioBroker.eusec#292]
### Adapter version

v0.9.5

### JS-Controller version

 4.0.23

### Node version

v16.18.1

### Operating System type

Linux

### Operating system version

Debian

### Describe the bug

Guten morgen @bropat,
habe gestern Abend auf die Version v0.9.5 aktualisiert von GitHub. Leider bekomme ich aber weiterhin den Fehler liegt es evtl. doch an mir das ich da was falsch mache?
Grüße
Fabio

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

ost.nuc
2022-11-06 06:30:03.114	error	instance system.adapter.eusec.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

eusec.0
2022-11-06 06:30:03.092	error	DB closed

eusec.0
2022-11-06 06:30:03.092	error	Error: DB closed at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:628:26) at Socket.emit (node:events:513:28) at TCP.<anonymous> (node:net:301:12)

eusec.0
2022-11-06 06:30:03.092	error	unhandled promise rejection: DB closed

eusec.0
2022-11-06 06:30:03.092	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

eusec.0
2022-11-06 06:30:03.092	error	DB closed

eusec.0
2022-11-06 06:30:03.092	error	Error: DB closed at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:628:26) at Socket.emit (node:events:513:28) at TCP.<anonymous> (node:net:301:12)

eusec.0
2022-11-06 06:30:03.092	error	unhandled promise rejection: DB closed

eusec.0
2022-11-06 06:30:03.092	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

eusec.0
2022-11-06 06:30:03.092	error	DB closed

eusec.0
2022-11-06 06:30:03.092	error	Error: DB closed at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:628:26) at Socket.emit (node:events:513:28) at TCP.<anonymous> (node:net:301:12)

eusec.0
2022-11-06 06:30:03.091	error	unhandled promise rejection: DB closed

eusec.0
2022-11-06 06:30:03.091	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

eusec.0
2022-11-06 06:30:03.089	warn	redis mget 0 28, err: Connection is closed.

eusec.0
2022-11-06 06:30:03.081	warn	redis mget 0 28, err: Connection is closed.

eusec.0
2022-11-06 06:30:01.459	info	Disconnected from station T8442P1021210257

eusec.0
2022-11-06 06:30:01.423	info	Disconnected from station T8010P2319390051

eusec.0
2022-11-06 06:30:01.266	info	Disconnected from station T8010N23214624A5

eusec.0
2022-11-06 06:30:01.008	info	Disconnected from station T8010N2321382394

eusec.0
2022-11-06 06:30:00.829	info	Disconnected from station T8010N231949117B

eusec.0
2022-11-06 06:30:00.560	info	Disconnected from station T8010N2319491071

eusec.0
2022-11-06 06:30:00.523	info	Disconnected from station T8010N2319490939

eusec.0
2022-11-06 06:30:00.523	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

eusec.0
2022-11-06 06:30:00.523	info	terminating

eusec.0
2022-11-06 06:30:00.522	info	Disconnect from station T8442P1021210257

eusec.0
2022-11-06 06:30:00.522	info	Disconnect from station T8010P2319390051

eusec.0
2022-11-06 06:30:00.521	info	Disconnect from station T8010N23214624A5

eusec.0
2022-11-06 06:30:00.521	info	Disconnect from station T8010N2321382394

eusec.0
2022-11-06 06:30:00.521	info	Disconnect from station T8010N231949117B

eusec.0
2022-11-06 06:30:00.521	info	Disconnect from station T8010N2319491071

eusec.0
2022-11-06 06:30:00.520	info	Disconnect from station T8010N2319490939

eusec.0
2022-11-06 06:30:00.520	info	Push notification connection closed

eusec.0
2022-11-06 06:30:00.514	info	Alarm mode for station T8010N23214624A5 changed to: HOME

eusec.0
2022-11-06 06:30:00.513	error	Cannot read properties of undefined (reading 'channel_list')

eusec.0
2022-11-06 06:30:00.512	error	TypeError: Cannot read properties of undefined (reading 'channel_list') at Station.getArmDelay (/opt/iobroker/node_modules/eufy-security-client/build/http/station.js:552:41) at Station.onAlarmMode (/opt/iobroker/node_modules/eufy-security-client/build/http/station.js:524:31) at P2PClientProtocol.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/build/http/station.js:35:57) at P2PClientProtocol.emit (node:events:513:28) at P2PClientProtocol.handleDataControl (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:1324:26) at P2PClientProtocol.handleData (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:1019:18) at P2PClientProtocol.parseDataMessage (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:1007:26) at P2PClientProtocol.handleMsg (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:839:26) at Socket.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:76:56) at Socket.emit (node:events:513:28)

eusec.0
2022-11-06 06:30:00.510	error	unhandled promise rejection: Cannot read properties of undefined (reading 'channel_list')

eusec.0
2022-11-06 06:30:00.510	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

eusec.0
2022-11-06 06:30:00.508	info	Alarm mode for station T8010N231949117B changed to: HOME

eusec.0
2022-11-06 06:30:00.477	info	Alarm mode for station T8010N2319491071 changed to: HOME

**Comment by sansonifabio** [comment]
Danke dir

**Comment by bropat** [comment]
@sansonifabio 

Dieser Teil vom Code wurde von einem User beigetragen und nicht direkt von mir geschrieben. Dieser Fehler sollte vom User behoben worden sein, aber anscheinend ist er noch vorhanden.
Werde mich nun selbst darum kümmern.

**Comment by bropat** [comment]
Der Fehler sollte nun in Version `0.9.6` behoben sein.

**Comment by sansonifabio** [comment]
Habe gerade die 0.9.6 installiert und getestet läuft bis jetzt Tip Top. Danke dir.;-)
